"""initial core schema

Revision ID: 54ad6d10f76f
Revises: 
Create Date: 2026-09-09 17:40:08.179958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ad6d10f76f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='semesterstatus'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_number')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_number')
    )
    op.create_table('billing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('schedule_snapshot', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENDING', 'SENT', 'FAILED', name='billingstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'student_id')
    )
    op.create_index(op.f('ix_billing_jobs_semester_id'), 'billing_jobs', ['semester_id'], unique=False)
    op.create_index(op.f('ix_billing_jobs_student_id'), 'billing_jobs', ['student_id'], unique=False)
    op.create_table('course_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'prerequisite_course_id')
    )
    op.create_table('offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('section_number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='offeringstatus'), nullable=False),
    sa.CheckConstraint('capacity >= 1', name='ck_offering_capacity_positive'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'course_id', 'section_number')
    )
    op.create_index(op.f('ix_offerings_course_id'), 'offerings', ['course_id'], unique=False)
    op.create_index(op.f('ix_offerings_semester_id'), 'offerings', ['semester_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('has_submitted', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('last_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester_id')
    )
    op.create_index(op.f('ix_schedules_semester_id'), 'schedules', ['semester_id'], unique=False)
    op.create_index(op.f('ix_schedules_student_id'), 'schedules', ['student_id'], unique=False)
    op.create_table('draft_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('PRIMARY', 'ALTERNATE', name='choicekind'), nullable=False),
    sa.Column('alternate_priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'alternate_priority'),
    sa.UniqueConstraint('schedule_id', 'offering_id')
    )
    op.create_index(op.f('ix_draft_choices_schedule_id'), 'draft_choices', ['schedule_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'course_id'),
    sa.UniqueConstraint('schedule_id', 'offering_id')
    )
    op.create_index(op.f('ix_enrollments_offering_id'), 'enrollments', ['offering_id'], unique=False)
    op.create_index(op.f('ix_enrollments_schedule_id'), 'enrollments', ['schedule_id'], unique=False)
    op.create_table('formal_alternates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'offering_id'),
    sa.UniqueConstraint('schedule_id', 'priority')
    )
    op.create_index(op.f('ix_formal_alternates_schedule_id'), 'formal_alternates', ['schedule_id'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Enum('A', 'B', 'C', 'D', 'F', 'I', name='gradevalue'), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'offering_id')
    )
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.create_table('offering_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.Column('end_period', sa.Integer(), nullable=False),
    sa.CheckConstraint('start_period >= 1 AND end_period >= start_period', name='ck_slot_period'),
    sa.CheckConstraint('weekday BETWEEN 1 AND 7', name='ck_slot_weekday'),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offering_slots_offering_id'), 'offering_slots', ['offering_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offering_slots_offering_id'), table_name='offering_slots')
    op.drop_table('offering_slots')
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_formal_alternates_schedule_id'), table_name='formal_alternates')
    op.drop_table('formal_alternates')
    op.drop_index(op.f('ix_enrollments_schedule_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_offering_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_draft_choices_schedule_id'), table_name='draft_choices')
    op.drop_table('draft_choices')
    op.drop_index(op.f('ix_schedules_student_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_semester_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_offerings_semester_id'), table_name='offerings')
    op.drop_index(op.f('ix_offerings_course_id'), table_name='offerings')
    op.drop_table('offerings')
    op.drop_table('course_prerequisites')
    op.drop_index(op.f('ix_billing_jobs_student_id'), table_name='billing_jobs')
    op.drop_index(op.f('ix_billing_jobs_semester_id'), table_name='billing_jobs')
    op.drop_table('billing_jobs')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('semesters')
    op.drop_table('courses')
    # ### end Alembic commands ###
