"""add teacher qualification and grade change tables

Revision ID: 686cacbbbda0
Revises: da4f6a565975
Create Date: 2026-09-16 15:45:28.851055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686cacbbbda0'
down_revision: Union[str, Sequence[str], None] = 'da4f6a565975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'course_id')
    )
    op.create_index(op.f('ix_teacher_qualifications_course_id'), 'teacher_qualifications', ['course_id'], unique=False)
    op.create_index(op.f('ix_teacher_qualifications_teacher_id'), 'teacher_qualifications', ['teacher_id'], unique=False)
    op.create_table('grade_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('previous_value', sa.Enum('A', 'B', 'C', 'D', 'F', 'I', name='gradevalue'), nullable=True),
    sa.Column('new_value', sa.Enum('A', 'B', 'C', 'D', 'F', 'I', name='gradevalue'), nullable=True),
    sa.Column('changed_by_teacher_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_teacher_id'], ['teachers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_changes_changed_by_teacher_id'), 'grade_changes', ['changed_by_teacher_id'], unique=False)
    op.create_index(op.f('ix_grade_changes_offering_id'), 'grade_changes', ['offering_id'], unique=False)
    op.create_index(op.f('ix_grade_changes_student_id'), 'grade_changes', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grade_changes_student_id'), table_name='grade_changes')
    op.drop_index(op.f('ix_grade_changes_offering_id'), table_name='grade_changes')
    op.drop_index(op.f('ix_grade_changes_changed_by_teacher_id'), table_name='grade_changes')
    op.drop_table('grade_changes')
    op.drop_index(op.f('ix_teacher_qualifications_teacher_id'), table_name='teacher_qualifications')
    op.drop_index(op.f('ix_teacher_qualifications_course_id'), table_name='teacher_qualifications')
    op.drop_table('teacher_qualifications')
    # ### end Alembic commands ###
